[install]
is_configured = 1

[ui]
is_visible = false

[launcher]
author = Phil Williams
description = "OPNsense TA: routes logs, performs priority mapping, includes functional lookups, and search-time field extractions."
version = 5.2.1
