# UDP input for OPNsense logs
[udp://515]
index = opnsense
no_appending_timestamp = true
no_priority_stripping = true

[script://$SPLUNK_HOME/etc/apps/TA-opnsense/bin/update_opnsense_lookup.py]
interval = 3600
sourcetype = opnsense:api:log
disabled = 0